/*
 *  survAUC_SongZhou.h
 *  survM
 *
 *  Created by Sergej Potapov on 14.10.10.
 *  Copyright 2010 __IMBE__. All rights reserved.
 *
 */

SEXP sens_SZ(SEXP THRESH, SEXP T, SEXP STIME, SEXP EVENT, SEXP N_TIME, SEXP LP, SEXP N_LP, SEXP LPNEW, SEXP N_LPNEW, SEXP TYPE_SENS);
SEXP spez_SZ(SEXP THRESH, SEXP T, SEXP STIME, SEXP EVENT, SEXP N_TIME, SEXP LP, SEXP N_LP, SEXP LPNEW, SEXP N_LPNEW);
SEXP auc_SZ(SEXP THRESH, SEXP T, SEXP STIME, SEXP EVENT, SEXP N_TIME, 
			SEXP STIME_NEW, SEXP EVENT_NEW, SEXP N_TIME_NEW, 
			SEXP LP, SEXP N_LP, SEXP LPNEW, SEXP N_LPNEW, SEXP TYPE_SENS);
